 
name: Deploy ASP.NET Core App on Server

on:
  push:
    branches: 
      - "main"     # ✅ Production

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop IIS (Production)
        run: iisreset /stop
        shell: cmd

      - name: Clear NuGet Cache
        run: nuget locals all --clear

      - name: Set NuGet Package Environment Variable
        run: echo "NUGET_PACKAGES=C:\nuget-packages" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore OnePortal-Api/OnePortal-Api.sln --packages C:\nuget-packages

      - name: Clean Build Artifacts
        run: dotnet clean OnePortal-Api/OnePortal-Api.sln --configuration Release

      - name: Build
        run: dotnet build OnePortal-Api/OnePortal-Api.sln --configuration Release --no-restore

      - name: Publish to Production
        run: dotnet publish OnePortal-Api/OnePortal-Api.csproj --configuration Release --output C:\Project\FN_Portal\Protal-API_Test\ --no-build

      - name: Restart IIS (Production)
        run: iisreset /restart
        shell: cmd
